float32 range            # meters
float32 v_rel_rad        # m/s, relative radial velocity
float32 az_ang0          # rad, possible azimuth angle 0
float32 az_ang1          # rad, possible azimuth angle 1
float32 el_ang           # rad, elevation angle
float32 rcs0             # dBm^2, possible radar cross section 0
float32 rcs1             # dBm^2, possible radar cross section 1
float32 prob0            # probability of azAng0 hypothesis
float32 prob1            # probability of azAng1 hypothesis
float32 range_var        # m^2, variance of range
float32 v_rel_rad_var    # (m/s)^2, variance of relative radial velocity
float32 az_ang0_var      # rad^2, variance of possible azimuth angle 0
float32 az_ang1_var      # rad^2, variance of possible azimuth angle 1
float32 el_ang_var       # rad^2, variance of elevation angle
float32 prob_false_alarm # probability if detection being false alarm
float32 snr              # dBr, signal to noise ratio
